services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    build:
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
